In [1]:
import networkx as nx
import numpy as np

In [2]:
G = nx.read_edgelist('pr.edgelist', create_using=nx.DiGraph(), nodetype=int)

n = G.number_of_nodes()

h0 = np.ones((n,1))
sum_h0 = h0.sum(axis=0)
print(h0)
print(sum_h0)

[[1.]
 [1.]
 [1.]
 [1.]]
[4.]


In [3]:
def matr(g):
    n= nx.number_of_nodes(g)
    A = nx.adjacency_matrix(g, nodelist=range(n), weight=None)
    A = A.todense()
    A = A.astype(float)
    M = A
    A = A.transpose()
    return A, M

In [4]:
def update(g, v, d, k):
    Mg = d*matr(g) + (1-d)*v
    M = Mg
    for i in range(0,k):
        M *= Mg
    M = M * v
    return M

In [5]:
matr(G)

(matrix([[0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [1., 1., 0., 1.],
         [0., 0., 0., 0.]]),
 matrix([[0., 1., 1., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.]]))

In [6]:
def HITS_update(G, h0, k):
    A, M = matr(G)
    auth = h0
    for i in range(0, k):
        auth = A*h0
        h0 = M*auth
        auth /= auth.sum(axis=0)
        h0 /= h0.sum(axis=0)
    return auth, h0

In [7]:
HITS_update(G, h0, 1)

(matrix([[0.2],
         [0.2],
         [0.6],
         [0. ]]),
 matrix([[0.36363636],
         [0.27272727],
         [0.09090909],
         [0.27272727]]))